### ISSUE TITLE
uninitialized constant UnserializeError

### ISSUE THREAD

**Issue by steverandy** [ndbroadbent/turbo-sprockets-rails3#1]
Using Rails 3.2.8

**Comment by ndbroadbent** [comment]
Thanks for the bug report! I've released a fix at `0.1.1`, so please run `bundle update turbo-sprockets-rails3` and try again.

**Comment by steverandy** [comment]
That was fast! It works now.

Thanks for making this awesome gem. assets_sync was the bottleneck of deployment.
