### ISSUE TITLE
cannot copy directory to itself error

### ISSUE THREAD

**Issue by veverkap** [ndbroadbent/turbo-sprockets-rails3#10]
I call rake assets:precompile without this gem included and it works great.  I add the gem and bundle install and get this error:

> Compiling: account/campaigns/index.js
> rake aborted!
> cannot copy directory /Users/veverkap/Code/threatsim/threatsim-rails/threatsim/public/assets/account to itself /Users/veverkap/Code/threatsim/threatsim-rails/threatsim/public/assets/account/campaigns/index.js/assets/account
> ...snip...
> Tasks: TOP => assets:precompile

**Comment by ndbroadbent** [comment]
Hi there, sorry about that! I've fixed this bug very recently, so please update to version `0.1.10` and let me know if that fixes your problem.

**Comment by nhalpern** [comment]
hi, I am running 0.1.10 and having the same issue mentioned above...
- executing "cd /home/rails/ma/releases/20121010202704 && bundle exec rake RAILS_ENV=staging RAILS_GROUPS=assets assets:precompile"
  servers: ["example.com"]
  [example.com] executing command
  *\* [out :: example.com] rake aborted!
  *\* [out :: example.com] 
  *\* [out :: example.com] cannot copy directory /home/rails/ma/releases/20121010202704/public/assets/icons-s4614205668.png to itself /home/rails/ma/releases/20121010202704/public/assets/icons-s4614205668.png/icons-s4614205668.png
  *\* [out :: example.com] 
  *\* [out :: example.com] 
  *\* [out :: example.com] Tasks: TOP => assets:precompile:all
  *\* [out :: example.com] 
  *\* [out :: example.com](See full trace by running task with --trace)
  *\* [out :: example.com] 
    command finished in 50712ms
  failed: "rvm_path=/usr/local/rvm /usr/local/rvm/bin/rvm-shell '1.9.3' -c 'cd /home/rails/ma/releases/20121010202704 && bundle exec rake RAILS_ENV=staging RAILS_GROUPS=assets assets:precompile'" on example.com

**Comment by veverkap** [comment]
By the way, this is working great now, thanks!
