### ISSUE TITLE
Changing an imported file (with Sass) doesn't trigger re-compile

### ISSUE THREAD

**Issue by PerfectlyNormal** [ndbroadbent/turbo-sprockets-rails3#13]
I created a small repo at [PerfectlyNormal/turbo-trouble](https://github.com/PerfectlyNormal/turbo-trouble) that demonstrates my problem.

`application.css.scss` and `print.css.scss` is precompiled, but they `@import "changeme";` and `@import "changeme2";` (my real app is obviously a bit more complex than this, but it is the importing that is the problem)

This works fine the first time, but when I change something in either `_changeme.scss` or `_changeme2.scss` and precompile, these changes isn't detected, and `application.css` and `print.css` isn't updated.

I was hoping it was some kind of easy way to fix this, without using Sprockets' `require`, since that doesn't seem to play well with variables and mixins from different files.

I'd like to keep using the gem, as it gives me a _very_ nice speed boost (from several minutes down to a few seconds!), so thanks for creating it!

**Comment by ndbroadbent** [comment]
You're a legend, thanks so much for the demo repo! That's a huge help. I've fixed this problem by manually including the source of `@imported` files from SASS templates (which also works recursively.)
It was either that or invoking the SASS processor, but the whole point of this gem is to avoid processing as much as possible.

Please try out the updated version at `0.1.11`, and let me know if it's working for you!

**Comment by ndbroadbent** [comment]
Sorry, one second - just fixing a bug...

**Comment by PerfectlyNormal** [comment]
Awesome, I'll give it a go asap tomorrow (11pm here, and I've shut down everything already :/)

**Comment by ndbroadbent** [comment]
Ok, great! I've fixed the bug, and also added support for Less `@import`s. Thanks again for opening the issue!

**Comment by ndbroadbent** [comment]
Oh, forgot to mention, please use version `0.1.12` when you update tomorrow. Cheers!

**Comment by PerfectlyNormal** [comment]
Hi. Sorry I haven't replied yet. Been super-busy. Gave it a quick spin, and it seems to be working fine now. Thanks!

**Comment by aaronjensen** [comment]
This seems to have regressed in 0.2.9. Only changes to the parent sass file actually trigger changes
