### ISSUE TITLE
Issue with premailer-rails3 gem

### ISSUE THREAD

**Issue by bradleypriest** [ndbroadbent/turbo-sprockets-rails3#17]
The `premailer-rails3` gem seems to be trying to compile my SCSS file on the fly in production mode and failing because of an @include statement rather than using the compiled version.

I assume https://github.com/fphilipe/premailer-rails3/blob/master/lib/premailer-rails3/css_loaders.rb#L34-76 is the offending code.

**Comment by ndbroadbent** [comment]
Hi there, I think this could be fixed in the latest version, where we stopped the 'tmp:create' task from clearing the assets cache. Could you please update and try again?

Thanks!

**Comment by bradleypriest** [comment]
Cool, that did the trick

**Comment by bradleypriest** [comment]
Ok, turns out that didn't fix it, reopening this so others can find it, hopefully I'll have some time to look into it soon

**Comment by bradleypriest** [comment]
More discussion on #28
