### ISSUE TITLE
Asset Sync does not work 

### ISSUE THREAD

**Issue by ravisraju** [ndbroadbent/turbo-sprockets-rails3#18]
The gem updates the manifest.yml file. It not just updates, but also changes the file format. It basically adds another level in the hash structure. Because of this, some gems like asset_sync which pushes the assets to storage fails. They assume that the manifest yml is a simple key value pair. Is it a fixable one ? Like using some other file rather than manifest.yml

**Comment by ndbroadbent** [comment]
Hi there, I've written about the `asset_sync` compatibility in the README. Here's the relevant section:

> asset_sync
> 
> Fully compatible. Just don't use the experimental AssetSync.config.manifest = true configuration option until my asset_sync patch has been merged.

Please either set `AssetSync.config.manifest = false`, or use `asset_sync` from my branch with the following line in your 'Gemfile':

``` ruby
gem "asset_sync", :github => "ndbroadbent/asset_sync", :branch => "new_manifest_support"
```

Thanks!

**Comment by ravisraju** [comment]
Great ! I have did the same changes to the asset_sync gem. Would have been great if the change was pulled in by rumblelabs. And, not using manifest.yml for asset sync will again slow down the deployment time defeating the purpose of this awesome gem. Thanks for your help

**Comment by ndbroadbent** [comment]
Ah, you might be misunderstanding the purpose of the manifest option. Here's the docs from the asset_sync README:

> Use the Rails generated 'manifest.yml' file to produce the list of files to
>    upload instead of searching the assets directory.

So you can turn it off, and it will just search your `public/assets` directory for files to upload. It will not recompile the assets, so it should be just as fast. Reading `manifest.yml` just ensures that asset_sync won't upload any unneeded files that happen to be in your `public/assets` directory, but there shouldn't be any unneeded files in there anyway.

**Comment by ravisraju** [comment]
oh ! I assumed searching through the directories would be slower and that was why manifest.yml was introduced. Good that got cleared up
