### ISSUE TITLE
ruby 1.9 only

### ISSUE THREAD

**Issue by jro** [ndbroadbent/turbo-sprockets-rails3#2]
There seems to be some uses of the ruby 1.9 hash syntax, so it might be good if the gem required it explicitly.

**Comment by ndbroadbent** [comment]
Hey, thanks for pointing that out! That was definitely unintentional. I've removed all instances of 1.9 hash syntax, as well as adding conditionals for other 1.9 features. I've released a new version @ `0.1.4`. 

The Rails 4.0.0 version only supports ruby `1.9.3`, but I want this gem to definitely support `1.8.7`.

Thanks again for letting me know, I appreciate it!
