### ISSUE TITLE
import scss not working for files without underscore

### ISSUE THREAD

**Issue by elfassy** [ndbroadbent/turbo-sprockets-rails3#21]
According to the sass documentation

@import "foo";

could import file foo.scss OR _foo.scss (not sure what logic is used if both are present)

```
"For example,
@import "foo.scss";
or
@import "foo";
would both import the file foo.scss"
```

Now turbo-sprockets-rails3 does not check for file changes on scss files without the leading underscore.

**Comment by ndbroadbent** [comment]
Hi there, this should all be fixed. Please update to `0.1.17` and let me know if you still experience any issues. Thanks!
