### ISSUE TITLE
Compass Sprites

### ISSUE THREAD

**Issue by aaronjensen** [ndbroadbent/turbo-sprockets-rails3#29]
Hi, I think we've come across another issue. Compass sprites do not get properly regenerated when one of the sprites changes or is added. I haven't had a chance to put together a repro yet, but we're not seeing changes. I'll post more info as I get it.

**Comment by ndbroadbent** [comment]
Are you importing sprites with something like `@import "my-icons/*.png";`? 

If it sees an `@import` anywhere in your asset, [this line](https://github.com/ndbroadbent/turbo-sprockets-rails3/blob/master/lib/sprockets/unprocessed_asset.rb#L18) will just fire the Sass compilation and it should pick up all the sprite changes. Please let me know if there's some more cases that we need to handle.

**Comment by aaronjensen** [comment]
We're not able to consistently repro and it may actually be a compass issue or with our setup. Closing until I can repro and actually point at turbo sprockets.

**Comment by aaronjensen** [comment]
For posterity, I believe the problem we were having was that we changed our compass `generated_images_dir` to `public/assets`. This caused compass to generate directly to `public/assets` so they were not considered part of the precompile. `turbo-sprockets-rails3` then would occasionally remove them during the `assets:clean_expired` step. 

To fix it, we set the `generated_images_dir` to `app/assets/images/sprites`

Because we use compass-rails we also had to re-monkey patch part of compass:

in `config/initializers/compass_sprites.rb`:

``` ruby
# compass-rails monkey patches this. We need to take it back
# so we can have our images in /sprites
Sass::Script::Functions.module_eval do
  def generated_image_url(path, only_path = nil)
    path = Sass::Script::String.new("sprites/#{path.value}")
    asset_url(path, Sass::Script::String.new("image"))
  end
end
```

**Comment by aaronjensen** [comment]
scratch all of this. It doesn't work at all. The problem is that compass sprites generates a file, it [does not get injected into the asset pipeline](https://github.com/chriseppstein/compass/issues/643) so the generated css files use the original non-digested file name. This causes turbo-sprockets to delete the file when an expire clean is done. 

The right way to do this is to set `generated_images_dir` to `app/assets/generated/sprites`,  add `app/assets/generated` to `.gitignore`, and add `config.assets.paths << Rails.root.join("app", "assets", "generated", "sprites")` to your application.rb

This seems to _actually_ be working. Whew.

**Comment by ndbroadbent** [comment]
Hi @aaronjensen, thanks for figuring this out! It's strange though, compass _should_ be adding it's sprites to the generated `manifest.yml` - See https://github.com/Compass/compass-rails/blob/stable/lib/compass-rails/patches/static_compiler.rb

I'm intentionally _not_ touching the `write_manifest` method in order to support the compass `alias_method_chain`, so it's weird that it's not working... The `assets:clean_expired` task should see those sprites being added to `manifest.yml`, and not touch them.

Can you let me know if the sprites are being added to `manifest.yml`? If not, the file I mentioned above would probably be a good place to debug.

Thanks!

**Comment by ndbroadbent** [comment]
P.S. Are you using the [compass-rails](https://github.com/Compass/compass-rails) gem?

**Comment by ndbroadbent** [comment]
Sorry, yeah you mentioned that in a comment above :P

**Comment by aaronjensen** [comment]
They are being added now. They didn't seem to be being added before when we were generating directly to public/assets.

**Comment by aaronjensen** [comment]
ok i'm being crazy fickle on this. It seems my previous solution doesn't work either. The problem is:

https://github.com/Compass/compass-rails/blob/stable/lib/compass-rails/railties/3_1.rb#L61

compass-rails requires you to have your generated sprites nested in your images path. If you don't you're SOL when it comes to manifest.yml generation. No sprites in your manifest and they get cleaned up.

I'm trying out only changing my sprite generation path in development and test only and leaving it default in all other environments. This seems to be working so far.

in `development.rb` and `test.rb`

``` ruby
  config.assets.paths << Rails.root.join("app", "assets", "sprites", "generated")
  config.compass.generated_images_dir = 'app/assets/sprites/generated'
```
