### ISSUE TITLE
odd gem version behavior

### ISSUE THREAD

**Issue by jjb** [ndbroadbent/turbo-sprockets-rails3#31]
I just did `bundle outdated` and was shown this:

```
  * turbo-sprockets-rails3 (0.3.2 > 0.1.16)
```

Then when I did `bundle update turbo-sprockets-rails3`, it only upgraded me to 0.2.12.

I don't see any dependencies in the gemspec that would result in this.

Any idea why this would be?

(thanks for a great project!)

**Comment by ndbroadbent** [comment]
Hi there, I've had to support different versions of sprockets, so `0.3.x` is only for the latest Rails 3.2.9. 
I'll add a note to the README about this, though. Thanks!
