### ISSUE TITLE
issue with 3.2.9 and heroku

### ISSUE THREAD

**Issue by jjb** [ndbroadbent/turbo-sprockets-rails3#33]
i was using turbo-sprockets-rails3 without the buildpack, just to get the other benefits.

it was working well with 0.1.16 and 3.2.8.

i just tried it with the newest version and 3.2.9, and the precompile step is skipped entirely.

let me know if you want any other info or if there is something i should try. thanks!

**Comment by ndbroadbent** [comment]
That's very strange, it should only skip the precompile step if it detects the presence of public/assets/manifest.yml, **or** your app doesn't have a `rake assets:precompile` task. These are heroku features and are unrelated to the gem. Can you check that you haven't checked in your assets, and let me know if `rake assets:precompile` is working on your local machine? Cheers

**Comment by jjb** [comment]
yep, no manifests, and precompile works locally. i just emailed you the output of my heroku push. let me know if oyu want any other info like my Gemfile.

to push some non-standard assets to s3 and stuff like that i have some `Rake::Task["assets:precompile:nondigest"].enhance do` blocks, not sure if that would affect anything.

**Comment by ndbroadbent** [comment]
Hi there,

Can you please confirm that precompile works properly when you remove
'turbo-sprockets-rails3' from your Gemfile?

On Fri, Nov 9, 2012 at 2:27 PM, John Joseph Bachir <notifications@github.com

**Comment by jjb** [comment]
```
➔ grep turbo-sprockets-rails3 Gemfile*
Gemfile:# https://github.com/ndbroadbent/turbo-sprockets-rails3/commit/8b422a974b19a3c91ad70e933bde45bcdede1ba0#commitcomment-2125121
Gemfile:# gem 'turbo-sprockets-rails3'
➔ foreman run bundle exec rake assets:precompile
/Users/john/.rbenv/versions/1.9.3-p286-perf/bin/ruby /Users/john/.rbenv/versions/1.9.3-p286-perf/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
foreman run bundle exec rake assets:precompile  142.82s user 19.29s system 70% cpu 3:50.62 total
➔
```

**Comment by ndbroadbent** [comment]
Sorry, I mean when you deploy to Heroku, does the precompile task run if `turbo-sprockets-rails3` is removed?

**Comment by jjb** [comment]
yes

**Comment by brendanstennett** [comment]
You may not actually get a benefit with this gem deploying on Heroku. Are your old compiled assets even accessible during deployment on Heroku since this is done in a tmp path?

**Comment by schneems** [comment]
@jjb, did you ever figure out what was causing this issue, is it still a problem?

**Comment by jjb** [comment]
@schneems no, didn't look into it further. I'm just going to wait until the standard buildpack supports this gem (which i think @ndbroadbent said is probably going to happen?)

**Comment by schneems** [comment]
I work for Heroku, and i'm in the process of vetting this gem and getting its support into the buildpack. It would be bad if we recommended something that kills people's assets:precompile task all-together. Is your app still on Heroku? Could you email me the app name richard.schneeman@gmail.com?

**Comment by jjb** [comment]
@schneems i think it was skipping the precompile step because it was assuming that it was being done locally, because i wasn't using the forked buidpack

i've never even tried it with the forked buildpack

(maybe you already knew all that)

would you still like my app name and/or for me to try it with the new buildpack?

**Comment by schneems** [comment]
Using any of the buildpacks, if it was skipping assets:precompile with the gem in and running assets:precompile without the gem, then that is something I would like to dig into. If you wouldn't mind, i'm still interested, please send it my way.

**Comment by jjb** [comment]
sent

**Comment by schneems** [comment]
@ndbroadbent you can close this, we found the issue with something else. @jjb ping back on this thread if you get to the point again where precompiling on Heroku works without the gem but fails with it.

**Comment by jjb** [comment]
will do

**Comment by ndbroadbent** [comment]
OK, that's good to hear! Closing

**Comment by jjb** [comment]
@schneems is this supported in the default buildpack yet?

**Comment by schneems** [comment]
not yet :(

**Comment by DouweM** [comment]
Any ETA?

**Comment by schneems** [comment]
ping @hone, any chance of getting the asset caching patch merged in?

**Comment by jjb** [comment]
@schneems @hone ping :-)

**Comment by iamnader** [comment]
@hone +1, would be great to get this in by default.  large asset directories take a really long time to deploy

**Comment by jjb** [comment]
@schneems @hone ping... :)

**Comment by jjb** [comment]
Here's the relevant pull request https://github.com/heroku/heroku-buildpack-ruby/pull/43 (right @ndbroadbent ?)
