### ISSUE TITLE
sources_manifest.yml not being generated

### ISSUE THREAD

**Issue by mixellent** [ndbroadbent/turbo-sprockets-rails3#37]
Just installed this neat gem, version 0.2.12 on rails version 3.2.8.
I also have asset_sync version 0.4.3 already installed.

Running rake assets:precompile RAILS_ENV=development works, but it does the regular way. I don't see any new file (sources_manifest) being generated.

Any clues?

**Comment by ndbroadbent** [comment]
Hi there,

I'm not sure if RAILS_ENV=development is the cause of your issue, but it
might be? Can you try creating a production database and running the task
normally with 'rake assets:precompile'?

Thanks!
Nathan

**Comment by mixellent** [comment]
Hi Nathan, 

I did try both the standard assets:precompile syntax as well as by adding RAILS_ENV=production but no luck. 
Maybe I will have to upgrade to rails 3.2.9 and try the newer version of this gem.

**Comment by mixellent** [comment]
UPDATE - seems to be working now, sources_manifest.yml now gets generated when I preocmpile my assets. Seems like it was an issue with the gem being specified in my :assets group in the Gemfile, and the following line being commented out in my application .rb:

``` ruby
Bundler.require(*Rails.groups(:assets => %w(development test)))
```

Once I ucommented this line, the gem started working.
