### ISSUE TITLE
0.3.3 asset precompile breaks for files with whitespace in filename

### ISSUE THREAD

**Issue by ghost** [ndbroadbent/turbo-sprockets-rails3#38]
in 0.3.3
you changed the command to update mtimes in
`lib/turbo-sprockets/tasks/assets.rake`

problem is the new command breaks if filename contains whitespace.

How to reproduce:
add asset file with name `ui-icons_222222_256x240 (copy)`
run `bundle exec rake assets:precompile --trace`
you will get:

```
** Execute assets:precompile:all
sh: 1: Syntax error: "(" unexpected
```

Next time you run assets:precompile it will precompile all assets from the beginning.

How to fix:
change line 82 of lib/turbo-sprockets/tasks/assets.rake
from `touch #{full_path}`
to `touch '#{full_path}'`
so that the whitespace in path is not treated as arguments delimeter.

**Comment by ndbroadbent** [comment]
Oh dear, that was a rookie mistake. Sorry about that, this should be fixed in version `0.3.4`, which I've just released.
