### ISSUE TITLE
0.3.4 is not effective on capistrano deploy

### ISSUE THREAD

**Issue by versum** [ndbroadbent/turbo-sprockets-rails3#39]
When using `0.3.4` with `gem "capistrano", :github => "ndbroadbent/capistrano", :branch => "assets_rollback_and_expiry"` precompilation is done from scratch on every deploy.

Capistrano is not throwing any errors is just that precompilation step is taking a long time (just as if turbo-sprockets were not present).

When I put `gem 'turbo-sprockets-rails3', '0.3.2'` in gemfile, deployment works as expected, precompilation is significantly faster.

Unfortunately I currently do not have time to investigate so I cannot propose a solution.

**Comment by ndbroadbent** [comment]
Hi there, my capistrano pull request has actually been merged into capistrano. Please try capistrano `2.13.5` and let me know if you are still experiencing any problems.

Please also try running `time rake assets:precompile` twice on your local machine, and let me know if both runs take the same amount of time.

**Comment by versum** [comment]
Capistrano `2.13.5` on rubygems does not have your asset recipe. 
It is merged on master but to use it I had to add to gemfile:
`gem 'capistrano', :github => 'capistrano/capistrano', :branch => 'master'`

Anyway it still breaks if I use turbo-sprockets-rails3 0.3.4.
On local machine asset precompilation works as expected in 0.3.4. 
When I deploy it to server using current capistrano master it has no effect on precompilation time.

Precompilation on deployment works if I switch to turbo-sprockets-rails3 0.3.2.

I tried deleting whole app directory from server and starting from scratch, it has no effect.

**Comment by ndbroadbent** [comment]
Sorry I haven't got back to you about this. Could you please try adding the following to `config/environments/production.rb`:

```
config.log_level = :debug
config.logger = Logger.new(STDOUT)
```

... and then deploying. You should see lots more info in the logs, so please let me know if you see anything strange.

Thanks!

**Comment by versum** [comment]
There is nothing unusual in the log.
Just "Updating mtimes for current assets..." and then precompilation takes just as long as it would without turbo-sprockets.
Manifest files are identical to those generated by 0.3.2, the command (rake assets:precompile) is the same yet something is wrong.

**Comment by ndbroadbent** [comment]
Hi there,

Please try version 0.3.5, it should now be a lot faster.

Thanks!
Nathan

**Comment by versum** [comment]
Hi,

My totally unscientific tests show 0.3.5 to be roughly the same as 0.3.2 in terms of assets compilation time.
Thank you for taking the time to address this issue, I'm closing it.
