### ISSUE TITLE
disable 1.8.7 on Travis?

### ISSUE THREAD

**Issue by benatkin** [ndbroadbent/turbo-sprockets-rails3#40]
The travis build is failing on ruby 1.8.7. Is that because you used a ruby 1.9 feature? If you remove it that would get it back to saying that it's passing on the README.

**Comment by ndbroadbent** [comment]
Hey, thanks for mentioning this! I just needed to peg the mocha version to get the tests passing on 1.8.7 :)
Everything is green again
