### ISSUE TITLE
Not much difference

### ISSUE THREAD

**Issue by rubystar** [ndbroadbent/turbo-sprockets-rails3#45]
I tried to precompile the assets on my local machine, but i couldn't  see much improvement

-sh-4.2$ time bundle exec rake assets:precompile
/usr/local/rvm/gems/ruby-1.9.3-p194@redzone/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `block in require': iconv will be deprecated in the future, use String#encode instead.
/usr/local/rvm/rubies/ruby-1.9.3-p194/bin/ruby /usr/local/rvm/gems/ruby-1.9.3-p194@redzone/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
/usr/local/rvm/gems/ruby-1.9.3-p194@redzone/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in`block in require': iconv will be deprecated in the future, use String#encode instead.

real    3m3.805s
user    2m5.093s
sys 0m6.321s
-sh-4.2$ time bundle exec rake assets:precompile
/usr/local/rvm/gems/ruby-1.9.3-p194@redzone/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `block in require': iconv will be deprecated in the future, use String#encode instead.
/usr/local/rvm/rubies/ruby-1.9.3-p194/bin/ruby /usr/local/rvm/gems/ruby-1.9.3-p194@redzone/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
/usr/local/rvm/gems/ruby-1.9.3-p194@redzone/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in`block in require': iconv will be deprecated in the future, use String#encode instead.

real    2m41.009s
user    1m27.802s
sys 0m38.563s
-sh-4.2$ 

You can see the difference is just 22 sec

Is it the whole benifit one can get or am i missing anything?

**Comment by ndbroadbent** [comment]
You should notice a bigger difference if you compile a second time. It wont make much difference on the first time.

**Comment by rubystar** [comment]
The difference between 1st and 2nd time is 22sec.
The difference between 2nd and 3rd time is negligible

The oveall compilation time is ~3min

**Comment by ndbroadbent** [comment]
Hi there, please try `0.3.5`, which should be a lot faster. Thanks!

**Comment by rubystar** [comment]
Hi,
    I tried the 0.3.5 version. It is doing better than the previous version but not much. The compilation time reduced to ~2min from ~3min. Do you have and numbers about this, like how much % of improvement we will get usually. I am using a custom UI gem, from where most of my assets will be loaded, so is it causing the issue?

I think i am missing something here, but i am not sure. If you want i can show you my gem file.

Thanks in Advance!

**Comment by rubystar** [comment]
Do you think using the latest capistrano code from the github repo will improve it anymore?

**Comment by ndbroadbent** [comment]
Hi there, sometimes it can take up to 1 minute for the Rails environment to load. So this gem can only do so much to speed up the compile process. Sorry, I don't know if anything else can be done to speed up your compile.
