### ISSUE TITLE
generate incorrect css file after deploy:rollback then deploy

### ISSUE THREAD

**Issue by lidaobing** [ndbroadbent/turbo-sprockets-rails3#46]
generate incorrect css file after deploy:rollback then deploy

**Comment by amalagaura** [comment]
Since assets have md5 sums, what exactly was incorrect?

**Comment by lidaobing** [comment]
the new release still use the old css file

**Comment by ndbroadbent** [comment]
Could you please try using the capistrano gem from the master branch in your Gemfile? I've added proper support for deploy:rollback in there, but a new version of capistrano hasn't been released with that feature. Please let me know if it works for you, thanks!
