### ISSUE TITLE
Css not getting compiled on heroku

### ISSUE THREAD

**Issue by pivotal-medici** [ndbroadbent/turbo-sprockets-rails3#5]
We just tried out the gem and it works awesomely fast locally. Great work!

However our application.css isn't getting compiled when we deploy to heroku (cedar). In the logs it says 

```
Compiled vendor.js  (90ms)  (pid 81956)
...
Compiled application.css  (5472ms)  (pid 81956)
```

But it doesn't list any of the css files above it like other resources. Locally we get the expected output. 

```
Compiled vendor.js  (90ms)  (pid 81956)
...
Compiled card/pdf/styles.css  (100ms)  (pid 81956)
Compiled card/text/styles.css  (102ms)  (pid 81956)
Compiled card/video/styles.css  (80ms)  (pid 81956)
Compiled application.css  (5472ms)  (pid 81956)
```

Our app is running 
- Ruby 1.9.3
- Rails 3.2.8
- Sprockets 2.1.3

**Comment by ndbroadbent** [comment]
Phew, this sounds like it could be a tough one.

What do you see when you run `heroku run bash`, and then `ls -l public/assets`? Is application.css missing, but the other assets are compiled?

Are you compiling both digest and non-digest assets, or have you turned off digests?

How are you requiring the `card/*/styles.css` files? Are you using normal directives in the head of application.css, or are you doing something like requiring them with methods in ERB? Are those files at `app/assets/stylesheets/cards/*/styles.css`, or somewhere else?

I don't think this is relevant, but Heroku will not recognise any file that's not compiled to `public/assets/`.

Can you think of any possible differences between your local environment, and Heroku? Maybe some ENV vars that change the behaviour of your rake tasks or environment? Oh, are you loading your Rails environment during asset compilation?

Sorry for so many questions, and these are all shots in the dark. It's very difficult to fix a bug that doesn't raise any exceptions :)

**Comment by ndbroadbent** [comment]
Hi again, I was wondering if this issue might be related to #6. If so, please try updating to `0.1.7` and see if that helps. Thanks!

**Comment by ndbroadbent** [comment]
Ah, here's an even more likely cause for your 'not compiled' issue. I've just added this note to the README:

> Warning: Don't add this gem to the `:assets` group in your Gemfile. It must be available in the production environment, since it overrides the asset path helpers and changes the manifest format. This is a common cause of `**** isn't precompiled` errors in production.

**Comment by pivotal-medici** [comment]
Not having it in the `:assets` group has done the job.

Cheers mate

**Comment by DouweM** [comment]
For anyone reading this and being as confused as I was, adding the gem to the `:assets` group is now actually the preferred method.
