### ISSUE TITLE
capistrano master still necessary?

### ISSUE THREAD

**Issue by thimios** [ndbroadbent/turbo-sprockets-rails3#50]
In the readme it is mentioned that compatibility with capistrano requires using the master branch of capistrano and not the latest release. Is it still a requirement?

thanks a lot

**Comment by arturtr** [comment]
Generally this point I also alarming. I do not want to update Capistrano with something stops working in assets precompile

**Comment by ndbroadbent** [comment]
A new version of Capistrano has been released, so the master branch is no longer necessary. README has been updated.
