### ISSUE TITLE
Cannot update to Rails 3.2.11

### ISSUE THREAD

**Issue by snikch** [ndbroadbent/turbo-sprockets-rails3#51]
I have had to remove `turbo-sprockets-rails3` as it has a railties dependency that is preventing me from upgrading to Rails 3.2.11.

Is it possible to get an updated version that isn't locked to railties < 3.2.9?

Cheers

```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    turbo-sprockets-rails3 (>= 0) ruby depends on
      railties (< 3.2.9, >= 3.1.0) ruby

    rails (= 3.2.11) ruby depends on
      railties (3.2.11)
```

**Comment by ndbroadbent** [comment]
Hi, please run `bundle update turbo-sprockets-rails3`. This should update it to version `0.3.6`, which has a railties dependency of `"> 3.2.8", '< 4.0.0'`.

**Comment by snikch** [comment]
Heh, thanks. I'd tried that, but I think I got stuck in a dependency issue. I ran `bundle update turbo-sprockets-rails3` and it told me I couldn't because I had Rails 3.2.11 in my gemfile, so I reverted that to Rails 3.2.8 (which is what I was upgrading from), then ran `bundle update turbo-sprockets-rails3` again, but since I was on Rails 3.2.8 - it didn't update!

Solution: Remove `turbo-sprockets-rails3`, Upgrade rails `3.2.8` -> `3.2.11`, Reinstall `turbo-sprockets-rails3`.

**Comment by ndbroadbent** [comment]
Ah, sorry about that!

I tried to release a different minor version for each Rails version, but
that's turned out to be more trouble than it's worth. Have been planning to
rewrite it so that all Rails versions can use the same version, and will
release 1.0.0 when that's done.

**Comment by snikch** [comment]
No need to apologise :D Thanks for the gem!

**Comment by mishrarohit** [comment]
Thanks @snikch for mentioning a solution.

**Comment by twalpole** [comment]
@snikch - for future reference you can pass multiple gems to update to bundler so
    bundle update rails turbo-sprockets-rails
should have done what you needed without having to remove gems, update, reinstall gems, etc

**Comment by snikch** [comment]
@twalpole Cheers. It was only by chance it happened to work, since I'd actually just given up on the gem, then when I received word in this thread that it should work, gave it another shot. Figured it out in hindsight.
