### ISSUE TITLE
rake task 'assets:clean_expired' not found on staging environment

### ISSUE THREAD

**Issue by johnkchow** [ndbroadbent/turbo-sprockets-rails3#58]
So on our staging box, when I execute the `rake -T` command, it doesn't list `assets:clean_expired` as an available task. However, on my local dev environment I see it.

I've included the `turbo-sprockets-rails` gem into the `:assets` group within my `Gemfile`.

I've tried running `RAILS_GROUPS=assets bundle exec rake -T` but that doesn't list it.

Not sure if I'm missing something or if I'm a total idiot. Any help would be appreciated!

BTW, love the work with the gem :)

**Comment by alexfalkowski** [comment]
Is this gone? or it just does it automatically now?

**Comment by ndbroadbent** [comment]
Hi there, I'm not sure why it's missing. I can see the task on our staging server by running: `RAILS_GROUPS=assets bundle exec rake -T`

I've also got the gem in the `:assets` group in our Gemfile. If you can run `assets:precompile` on your server, then I think you should be able to also run `assets:clean_expired`

**Comment by ndbroadbent** [comment]
Ahh, I might have actually re-added the task in the last 7 months. Sorry for the super-delayed response!

**Comment by alexfalkowski** [comment]
when I do `bundle exec rake assets:clean_expired` it complains as not being there. This was today.

**Comment by ndbroadbent** [comment]
Please try running: `RAILS_GROUPS=assets bundle exec rake
assets:clean_expired`

**Comment by alexfalkowski** [comment]
Ahh thanks :)
