### ISSUE TITLE
Is a custom Heroku build pack still necessary?

### ISSUE THREAD

**Issue by nathany** [ndbroadbent/turbo-sprockets-rails3#77]
See https://devcenter.heroku.com/changelog-items/328

**Comment by ndbroadbent** [comment]
Hi there, yes the custom Heroku build pack is still necessary for turbo-sprockets-rails3. Heroku is caching a different folder for Rails 4 (tmp/assets/cache), while turbo-sprockets-rails needs to preserve the actual assets directory (public/assets)
