### ISSUE TITLE
Rails 4: Uninitialized constant Sprockets::Bootstrap

### ISSUE THREAD

**Issue by saizai** [ndbroadbent/turbo-sprockets-rails3#78]
```
$ rake assets:precompile
/Users/saizai/.rvm/rubies/ruby-2.0.0-p247/bin/ruby /Users/saizai/.rvm/gems/ruby-2.0.0-p247/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
rake aborted!
uninitialized constant Sprockets::Bootstrap
/Users/saizai/.rvm/gems/ruby-2.0.0-p247/gems/turbo-sprockets-rails3-0.2.9/lib/turbo-sprockets/tasks/assets.rake:186:in `block (2 levels) in <top (required)>'
...
```

**Comment by ndbroadbent** [comment]
Hi there,

turbo-sprockets-rails3 is only for Rails 3. It is not required for Rails 4. Sorry for the confusion!

**Comment by ndbroadbent** [comment]
Sorry again, I wonder if you could please try out this suggestion: https://github.com/capistrano/capistrano/issues/478#issuecomment-24983528

If removing the mtime task fixes it, we should get rid of it in capistrano.

**Comment by saizai** [comment]
@ndbroadbent Tried it. Runtimes for precompile on successive identical deployments:
1st 67235ms
2nd 38400ms
3rd 51423ms
