### ISSUE TITLE
Changed assets don't get pushed to s3 via assetsync

### ISSUE THREAD

**Issue by courtsimas** [ndbroadbent/turbo-sprockets-rails3#8]
Rails 3.2.8 on heroku.

This may be somehow unique to my setup, but I can't get any new assets to push up - ever. It will run through the whole compilation list when deploying to heroku, and yes it is half the time due to the the process only running once, and not twice.... but new files simply won't go up. They never get uploaded to s3. I have a pretty standard config.

**Comment by krainboltgreene** [comment]
Had this same problem. No errors either.

**Comment by ndbroadbent** [comment]
Hi, sorry about that, this was due to the way I was rewriting the rake tasks. I have fixed this issue and pushed a new version at `0.1.8`. Please update and try again, and let me know if your problem is solved. Sorry again!

**Comment by courtsimas** [comment]
Solved :)
