### ISSUE TITLE
Plans for rails 4?

### ISSUE THREAD

**Issue by cyrusstoller** [ndbroadbent/turbo-sprockets-rails3#80]
This is awesome. Thank you for all the hard work. 

What needs to be done for this to be rails 4 compatible? Or is there already a way to use it with rails 4?

**Comment by ndbroadbent** [comment]
Hello,

As far as I'm aware, this gem shouldn't be necessary at all for Rails 4. The people working on assets have made a few changes that means that asset caches can be reused between compiles, and it can even re-use a warm cache from your development environment.

Best,
Nathan

**Comment by cyrusstoller** [comment]
@ndbroadbent That's awesome. Thank you.
