### ISSUE TITLE
Heroku deploy errors after ruby update(using buildpack)

### ISSUE THREAD

**Issue by arfl** [ndbroadbent/turbo-sprockets-rails3#84]
After the update on ruby 2.1.0 I get following errors:

```
-----> Ruby/Rails app detected
 !
 !     Invalid RUBY_VERSION specified: ruby-2.1.0
 !     Valid versions: ruby-2.0.0, ruby-1.9.3, ruby-1.9.2, ruby-1.8.7, ruby-1.9.3-jruby-1.7.0, ruby-1.8.7-jruby-1.7.0, ruby-1.9.3-jruby-1.7.1, ruby-1.8.7-jruby-1.7.1, ruby-1.9.3-rbx-2.0.0dev, ruby-1.8.7-rbx-2.0.0dev
```

Removing the buildpack fixes it again.

**Comment by macowie** [comment]
Just bumped ruby versions on a project and got this too.

**Comment by arfl** [comment]
Sorry, had to mention the fix before closing this issue.
I used this buildpack and it ran again https://github.com/ndbroadbent/heroku-buildpack-turbo-sprockets/pull/5

**Comment by macowie** [comment]
Ah! Thank you.
