### ISSUE TITLE
rake assets:precompile doesn't stop

### ISSUE THREAD

**Issue by aquach** [ndbroadbent/turbo-sprockets-rails3#9]
I'm getting an issue where the precompilation process is stuck. When I `strace` the ruby process, I see that it's doing something crazy where it's making a ton of nested directories, like this:

```
public/assets/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/merchants/stores-3180d34769b49d5780b4651b7dc72004.js.gz
```

I'm not sure what information about the way my Javascript assets are laid out would be useful to debug this, but I'm on version `0.1.7` installed with `bundle`.

**Comment by ndbroadbent** [comment]
Oh dear. Can you please post the output of `puts
Rails.application.config.assets.inspect` from `rails console`?

Also, would you be comfortable sending me a .zip of your application's
Gemfile and app/assets folder? Totally understandable if not, but that
would probably help me get to the root of the problem really fast.
If so, my email is nathan.f77 at gmail dot com

On 6/10/2012, at 9:56 AM, Alex Quach notifications@github.com wrote:

I'm getting an issue where the precompilation process is stuck. When I
strace the ruby process, I see that it's doing something crazy where it's
making a ton of nested directories, like this:

public/assets/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/email/index.js/merchants/stores-3180d34769b49d5780b4651b7dc72004.js.gz

I'm not sure what information about the way my Javascript assets are laid
out would be useful to debug this, but I'm on version 0.1.7 installed with
bundle.

—
Reply to this email directly or view it on
GitHubhttps://github.com/ndbroadbent/turbo-sprockets-rails3/issues/9.

**Comment by aquach** [comment]
This project is for a company, so I don't think I can zip the assets. But here's the output of the `puts` command, JSON'd and with my project root replaced with `PROJECT_ROOT`. I'm assuming you want `RAILS_ENV=production` because that's the environment I set when compiling.

```
{
    "cache_store": [
        "file_store", 
        "PROJECT_ROOT/internal/tmp/cache/assets/"
    ], 
    "compile": false, 
    "compress": true, 
    "css_compressor": null, 
    "debug": false, 
    "digest": true, 
    "enabled": true, 
    "initialize_on_precompile": true, 
    "js_compressor": null, 
    "logger": null, 
    "manifest": null, 
    "paths": [
        "PROJECT_ROOT/internal/app/assets/images", 
        "PROJECT_ROOT/internal/app/assets/javascripts", 
        "PROJECT_ROOT/internal/app/assets/stylesheets", 
        "PROJECT_ROOT/internal/app/assets/templates", 
        "PROJECT_ROOT/internal/vendor/assets/images", 
        "PROJECT_ROOT/internal/vendor/assets/javascripts", 
        "PROJECT_ROOT/internal/vendor/assets/stylesheets", 
        "PROJECT_ROOT/core/vendor/assets/images", 
        "PROJECT_ROOT/core/vendor/assets/javascripts", 
        "PROJECT_ROOT/core/vendor/assets/sprites", 
        "PROJECT_ROOT/core/vendor/assets/stylesheets", 
        "PROJECT_ROOT/core/vendor/assets/templates"
    ], 
    "precompile": [
        {}, 
        "application.js", 
        "login.js", 
        "lib/jquery/jquery.min.js", 
        "lib/jquery/jquery.ui.droppable.min.js", 
        "lib/jsonreport.js", 
        "moderation/moderation.js"
    ], 
    "prefix": "/assets", 
    "version": "1.0"
}
```

I've got a project called `internal` which uses a gem called `core`. They're siblings in the same directory. `core` has assets in `core/vendor/assets` which Sprockets automagically includes in the search path. Templates are an extra path I add to compile Handlebars templates. Hope you can get to the root of this and sorry I can't send you our code!

**Comment by ndbroadbent** [comment]
Hi, thanks for posting your config!

I've just noticed a recent commit to Rails 3.2.9 (https://github.com/rails/rails/commit/19987b64af0d543a6292c3fd9b0b877f70eab306) that might be able to solve your problem. I've pushed the change to a temporary branch on `turbo-sprockets-rails3`, and it would be awesome if it you could help me test it out. Please replace the gem in your Gemfile with the following line:

```
gem 'turbo-sprockets-rails3', :git => 'https://github.com/ndbroadbent/turbo-sprockets-rails3.git', :branch => 'issue_9'
```

**Comment by aquach** [comment]
Great! That worked really well ‒ cut my precompile time to a third of what it used to be! Thanks for making a branch for me. What's the best way to make this fix permanent? Will you leave this in the gem or have people upgrade to 3.2.9?

**Comment by ndbroadbent** [comment]
Oops, the solution was actually a lot easier... It turned out to be an oversight in the non-digest generator, where I didn't keep the `*/index.*` behavior consistent.

Could you please confirm that the updated version of the gem at `0.1.10` also resolves your issue? Thanks so much for your help!

P.S. I've decided to keep the assets behavior consistent with 3.2.8 for now, and I will update my gem to handle the new behavior when 3.2.9 is released.

**Comment by aquach** [comment]
Great! Seems to work. Thanks so much for the quick response. Time to put this in all my projects.
